version: "3"

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception-network
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    environment:
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - wordpress-volume:/var/www/html
    restart: unless-stopped
    networks:
      - inception-network

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/html
    restart: unless-stopped
    networks:
      - inception-network
      
volumes:
  mariadb-volume:
  wordpress-volume:

networks:
  inception-network:
    driver: bridge
